manifest:
  remotes:
    - name: splitkb
      url-base: https://github.com/splitkb
  projects:
    - name: zmk
      remote: splitkb
      revision: main+halcyon-fixes
      import: app/west.yml
    - name: zmk-driver-charge-led
      remote: splitkb
      revision: main
    - name: zmk-driver-vik-sleep
      remote: splitkb
      revision: main
  self:
    path: config
